### ISSUE TITLE
Doubt in ReactJS take-home-test regarding the name of library.

### ISSUE THREAD

**Issue by KushagraMehta** [wednesday-solutions/take-home-test#2]
In [ReactJS assignment](https://github.com/wednesday-solutions/take-home-test/blob/master/react.md) there is a _should have_ list. In which **React-into for localisation** is given but I think there is a spelling mistake it should be **[React-intl](https://www.npmjs.com/package/react-intl) for localization**. 
I'm confused with the name of the library please correct me if I'm wrong.

**Comment by alichherawalla** [comment]
yup, that's correct. There was a typo that has now been fixed.
